### PR TITLE
Make numpy array contiguous

### PR DESCRIPTION
**Pull request by ollieglass**
I'm using sklearn with pandas, as many people do. The numpy matrix in the pandas dataframe isn't contiguous; this pull request makes it so, so it will work with the compiled predictor.

I think the best long term solution for prediction data issues like this is to use the existing sklearn input validators (like https://github.com/scikit-learn/scikit-learn/blob/412996f09b6756752dfd3736c306d46fca8f1aa1/sklearn/utils/validation.py#L272), but that's beyond me right now. This is a quick fix that will hopefully make using compiled trees easier for many people.

### CODE REVIEW

**Comment by mwojcikowski** [comment]
Can you add an unittest for that? Thanks.

**Comment by ollieglass** [comment]
Sure, test added

**Comment by mwojcikowski** [comment]
One minor suggestion: can you use `assert_equal` to compare results from non-contiguous and float32 input to c-contiguous and float64 instead of the `try: .. except:` syntax. At least that's the convention used in this project (inspired by `scikit-learn` I guess).

**Comment by ollieglass** [comment]
Sure, changes pushed. I am intending something different with the try / except though, it's to check that the non-contiguous array doesn't raise a ValueError. I don't find the syntax intuitive, but apparently that's the recommended way to assert that an exception _isn't_ thrown http://stackoverflow.com/a/4319870/160406

There's three things happening in the test now: 
1. check ValueError isn't raised
2. check results are the same as for a contiguous array, and
3. check a float64 contiguous array gives the same results as a float32 non-contiguous array

I think these would be better separated

**Comment by ollieglass** [comment]
Separated 3 into it's own test. I think 1 and 2 are fine together.

What do you think?

**Comment by mwojcikowski** [comment]
They look fine to me.

**Pull request merged**
